#!/usr/bin/csh

setenv DIHIGGS_PATH ${HOME}/diHiggs

cp -r ${DIHIGGS_PATH}/. ${_CONDOR_SCRATCH_DIR}
cd ${_CONDOR_SCRATCH_DIR}
echo "PWD = ${PWD}"


cp INPUTFILE ./code/selection/selection_input.root

echo "..Copying INPUTFILE -> ./code/selection/selection_input.root"

source code/setup.csh

cd code/selection
root -l -b Selection.C

cd  ${_CONDOR_SCRATCH_DIR}


cp ./code/selection/selection_output.root ./code/hhDilep_pseudoanasol/data/pdf_input.root
echo "..Copying ./code/selection/selection_output.root -> ./code/hhDilep_pseudoanasol/data/pdf_input.root"

cd ./code/hhDilep_pseudoanasol
echo "PWD = ${PWD}"

gmake clean
gmake main.x
./main.x


cp ./data/pdf_output.root OUTPUTFILE


echo "..Copying ./data/pdf_output.root -> OUTPUTFILE"



cd ${_CONDOR_SCRATCH_DIR}
echo "PWD = ${PWD}"